//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KosarkaDbContainerContext : DbContext
    {
        public KosarkaDbContainerContext()
            : base("name=KosarkaDbContainerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Takmicenje> Takmicenjes { get; set; }
        public virtual DbSet<Kup> Takmicenjes_Kup  { get; set; }
        public virtual DbSet<Liga> Takmicenjes_Liga { get; set; }
        public virtual DbSet<Kosarkas> Kosarkas { get; set; }
        public virtual DbSet<Plejmejker> Kosarkas_Plejmejker { get; set; }
        public virtual DbSet<BekSuter> Kosarkas_BekSuter { get; set; }
        public virtual DbSet<Krilo> Kosarkas_Krilo { get; set; }
        public virtual DbSet<KrilniCentar> Kosarkas_KrilniCentar { get; set; }
        public virtual DbSet<Centar> Kosarkas_Centar { get; set; }
        public virtual DbSet<Ucestvuje> Ucestvujes { get; set; }
        public virtual DbSet<Trofej> Trofejs { get; set; }
        public virtual DbSet<Klub> Klubs { get; set; }
    }
}
