//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucestvuje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ucestvuje()
        {
            this.Trofejs = new HashSet<Trofej>();
        }
    
        public int Takmicenje_IdTakmicenja { get; set; }
        public int Klub_IdKluba { get; set; }
    
        public virtual Takmicenje Takmicenje { get; set; }
        public virtual Klub Klub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trofej> Trofejs { get; set; }
    }
}
